### ISSUE TITLE
I cannot build mf6.exe using pymake

### ISSUE THREAD

**Issue by hjia1005** [MODFLOW-USGS/modflow6#844]
Hi, I am very eager to try out the new tvk and tvs packages with the develop version of mf6, but when I follow the instructions to build the latest mf6.exe, I keep getting the below error. Any help will be appreciated.

## Code to build exe:
import pymake
pm = pymake.Pymake()
pm.srcdir = '../src'
pm.target = 'mf6'
pm.include_subdirs = True
pm.build()

## Error message:
compiling...mf6.exe

Compiling object files for 'mf6.exe'...
gfortran -O2 -static -fbacktrace -D_WIN32 -Wtabs -Wline-truncation -Wunused-label -Wunused-variable -pedantic -std=f2008 -Wcharacter-truncation -I.\obj_temp -J.\mod_temp -c src_temp\Utilities\OpenSpec.f90 -o .\obj_temp\OpenSpec.o
Traceback (most recent call last):

  File "C:\Users\jiaha\AppData\Local\Temp/ipykernel_8240/4262047055.py", line 6, in <module>
    pm.build()

  File "C:\DDrive\anaconda\lib\site-packages\pymake\pymake.py", line 786, in build
    self.returncode = main(

  File "C:\DDrive\anaconda\lib\site-packages\pymake\pymake_base.py", line 256, in main
    returncode = _pymake_compile(

  File "C:\DDrive\anaconda\lib\site-packages\pymake\pymake_base.py", line 959, in _pymake_compile
    proc = _process_Popen_initialize(cmdlist, intelwin)

  File "C:\DDrive\anaconda\lib\site-packages\pymake\utils\_Popen_wrapper.py", line 32, in _process_Popen_initialize
    return Popen(cmdlist, stdout=PIPE, stderr=stderr)

  File "C:\DDrive\anaconda\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File "C:\DDrive\anaconda\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,

  File "C:\DDrive\anaconda\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,

FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by jdhughes-usgs** [comment]
@hjia1005 not sure what the problem is. Is `gfortran` available from the command line/terminal? You will have to run from a `mingw` terminal if you haven't added  `C:\MinGW\bin` to your path.

If you pull down the latest develop branch you can use the makefile to build `mf6` without `pymake`. That will let you know if it is a `python` or `gfortran` issue.
