### ISSUE TITLE
accessing boundnames thru the API

### ISSUE THREAD

**Issue by jtwhite79** [MODFLOW-USGS/modflow6#856]
Im sure Im doing something wrong but I cannot access boundnames thru the API:
```
Traceback (most recent call last):
File "../code/mf6cts.py", line 586, in _read_cts_input_file
names = self._gwf.get_value(wbaddr)
File "/Users/JWhite/opt/miniconda3/lib/python3.8/site-packages/xmipy-1.0.0-py3.8.egg/xmipy/xmiwrapper.py", line 281, in get_value
rank = self.get_var_rank(name)
File "/Users/JWhite/opt/miniconda3/lib/python3.8/site-packages/xmipy-1.0.0-py3.8.egg/xmipy/xmiwrapper.py", line 237, in get_var_rank
self.execute_function(
File "/Users/JWhite/opt/miniconda3/lib/python3.8/site-packages/xmipy-1.0.0-py3.8.egg/xmipy/xmiwrapper.py", line 633, in execute_function
raise XMIError(msg)
xmipy.errors.XMIError: MODFLOW 6 BMI, exception in: get_var_rank (for variable GWF/WEL_0/BOUNDNAME)
```
I can see boundnames in the mem mgr reporting and I can access other vars like `NODELIST` and `RHS`.  Is there something special to do for boundnames?

thanks!

**Comment by langevin-usgs** [comment]
This should be closed with PR #1023.
